fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: detect-private-key
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: ^venv/ ^.git/ ^.vscode/ ^.DS_Store 
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy 
        language: system
        types: [python]
        exclude: ^venv/ ^.git/ ^.vscode/ ^.DS_Store 
